### ISSUE TITLE
Finish setting up GitHub

### ISSUE THREAD

**Issue by sjohandup** [Valknut-Software-Engineering/Capstone_Project#1]
- Landing Page
- Folder structure
- Scrum board (Trello/ZenHub)

**Comment by BernhardSchuld** [comment]
@sjohandup For future reference, rather split up the sub-tasks into individual issues. Because I'm done with the Scrum Board setup, but I don't know how far the Landing Page and Folder Structure tasks are. And it's harder to estimate a collection of tasks.
