### ISSUE TITLE
Documentation(main)

### ISSUE THREAD

**Issue by sjohandup** [Valknut-Software-Engineering/Capstone_Project#2]
Latex document that will link up and combine all other sub documentation files

**Comment by BernhardSchuld** [comment]
@sjohandup & @MasterJetson Could one of you add an estimate to this issue? I don't know how long you guys have been working on it nor how long the estimated total is. I think you guys should have a better grasp on the Estimate than myself. Each Story point is equal to one hour.

**Comment by sjohandup** [comment]
@BernhardSchuld  I'm actually close to finishing it, but where do I add the Estimate? 😅

**Comment by BernhardSchuld** [comment]
@sjohandup To the right, where the assignees, labels etc is. There is an Estimate option. Below Milestone

**Comment by sjohandup** [comment]
@BernhardSchuld it's not showing on my side.  Which is strange, because I do have the ZenHub add-on.  I even disabled/enabled it to see if it would help 😅 
For now though do you mind adding it for me?  I should be done with it within the next 20 minutes.  You can set it as 1 story point.  😅
