### ISSUE TITLE
Documentation(Guidelines-and-Rules)

### ISSUE THREAD

**Issue by BernhardSchuld** [Valknut-Software-Engineering/Capstone_Project#3]
Need to set up and reach consensus on the Guidelines and Rules document that is going to be used during the duration of the project

**Comment by BernhardSchuld** [comment]
@PeteElite @MasterJetson @sjohandup @Mazzl3s I will start creating the document later tonight or tomorrow morning. When I'm done, I would like for everyone to review it and give input so that we can reach consensus on the rules and guidelines (after the 12:00 demo). The consensus is very important because these guidelines and rules will dictate how we go about working for the rest of the project.

**Comment by sjohandup** [comment]
Agreed 👌
