### ISSUE TITLE
Unity-Engine-Keybindings/user-keybindings-fo-manipulation

### ISSUE THREAD

**Issue by Mazz1es** [Valknut-Software-Engineering/Capstone_Project#42]

**Comment by sjohandup** [comment]
Good day all.
Just a list of the current KeyCodes I have used thus far:

|    KeyCode  |  Description |
|------------ | --------------- |
| C | Clone Object |
| E | Pick Up / Put Down |
| F | Float Object |
| G | Toggle SnapToGrid |
| Q | Toggle Rotation Offset |
| Tab | Toggle IsPickUpable |
| Delete | Destroy Object |
| Keypad0 | Spawn Default Cube |

**Comment by sjohandup** [comment]
Link to a list of unity KeyCodes

https://docs.unity3d.com/ScriptReference/KeyCode.html
